DROP TABLE IF EXISTS City_list;
CREATE TABLE City_list (
    City	VARCHAR(512),
    Manger	VARCHAR(512)
);

INSERT INTO City_list (City, Manger) VALUES ('Leeds', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('West Bromwich', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Le Bouscat', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Strasbourg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Aachen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Thiais', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Delhi', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Milan', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Brandenburg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Heilbronn', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Mumbai', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Swindon', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Puertollano', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hyderabad', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sonneberg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Alphen aan den Rijn', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Littlehampton', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Taverny', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Pune', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Nacka', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Manchester', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Viroflay', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Murcia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Karlsruhe', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Madrid', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Rome', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Stuttgart', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Mansfield', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Newcastle upon Tyne', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Paris', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Dijon', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Hasselt', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Vienna', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Sabadell', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Argentan', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Stourbridge', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Nuremberg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Southend-on-Sea', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cambridge', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rugby', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bayeux', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Genis-Laval', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pantin', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hamburg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Beaune', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Antibes', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Houilles', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Cesena', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Namur', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Marano di Napoli', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('London', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dundee', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wiesbaden', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vitry-sur-Seine', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Villiers-le-Bel', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Castelldefels', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Abbeville', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Tarragona', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Durrus', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Santander', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Amadora', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Berlin', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('San Fernando', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Brest', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Trier', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Ulm', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Nancy', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Cannes', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Alkmaar', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Pontault-Combault', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Sheffield', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Marseille', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Basildon', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('San Sebastian', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Granada', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Barry', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bedford', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pessac', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Irun', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Mantes-la-Jolie', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Celle', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bisceglie', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Albertville', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Birmingham', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Perpignan', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Vigneux-sur-Seine', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Estepona', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Fontenay-aux-Roses', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Deuil-la-Barre', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Burgos', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Moncalieri', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Chilly-Mazarin', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Amiens', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Chester', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sant Boi de Llobregat', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Metz', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Antony', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Drancy', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Arnsberg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Offenbach', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cerignola', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Grasse', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Munich', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gateshead', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Issy-les-Moulineaux', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Nazaire', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Chemnitz', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Naples', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Coulommiers', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Uppsala', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bergen op Zoom', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Brieuc', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Trapani', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Poole', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Evry', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Aulnay-sous-Bois', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Haguenau', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Harrogate', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ermont', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Colmar', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Palma de Mallorca', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Capelle aan den IJssel', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Stockholm', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Castellammare di Stabia', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Belfort', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Burnley', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Linz', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Salzburg', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Alicante', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montfermeil', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Vitoria', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Sittard', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bergheim', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bergisch Gladbach', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Dresden', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bielefeld', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rudge', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Northampton', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Champigny-sur-Marne', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Avignon', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bolzano', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Washington', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Talence', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Palaiseau', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Pertuis', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Karlstad', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dewsbury', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Huddinge', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Delft', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Dordrecht', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Amstelveen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Livry-Gargan', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Schiltigheim', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ludwigsfelde', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Levallois-Perret', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Taranto', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Tours', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Woking', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bezons', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Vincennes', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Sarcelles', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Huddersfield', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('La Crau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Stafford', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Moissy-Cramayel', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Seville', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Chartres', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Turku', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Leipzig', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Limoges', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Assen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Valence', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bury', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Messina', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Luton', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bordeaux', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Great Yarmouth', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Fontaine', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Parla', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Villeneuve-sur-Lot', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Verona', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bochum', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Apeldoorn', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Glasgow', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Argenteuil', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Sassari', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Villeurbanne', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bourges', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Mont-de-Marsan', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Esbjerg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Nice', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Pforzheim', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Florence', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Matosinhos', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Ravenna', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Augsburg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Pozzuoli', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Sandnes', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Valencia', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rimini', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Neubrandenburg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Wetzlar', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Edinburgh', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Antwerp', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Les Lilas', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Zurich', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Magdeburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Ouen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Slough', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Catania', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Monza', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Avold', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Espoo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carlisle', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Mâcon', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Villach', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Harlow', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cergy', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rotherham', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Zwickau', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Osny', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Odense', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Arras', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Gosport', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Lund', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Marignane', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Neuilly-sur-Seine', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Leicester', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Wigan', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Fiumicino', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Foggia', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Muret', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Baden-Baden', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Benidorm', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cormeilles-en-Parisis', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Malo', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Nanterre', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Domont', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Conflans-Sainte-Honorine', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Elda', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Meyzieu', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Aprilia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hankerton', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Molina de Segura', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Jena', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Cagliari', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Cholet', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Colchester', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Aschaffenburg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Helsinki', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Sevran', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Maidstone', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Las Rozas de Madrid', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montesson', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bari', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Avion', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Eakring', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Kiel', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Priest', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Cloud', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Clint cum Hamlets', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Hastings', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Le Plessis-Robinson', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Nantes', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Fareham', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Novara', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Montargis', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Montpellier', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Toulouse', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Denis', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Ercolano', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ceuta', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Angers', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Seraing', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('South Shields', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Epinal', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Gothenburg', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Molfetta', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Salamanca', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Torrevieja', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Genoa', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Cuxhaven', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Yerres', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Albacete', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Nijmegen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Vicenza', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Boulogne-Billancourt', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Lyon', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Stoke-on-Trent', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Beauvais', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Vannes', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Hilden', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Clamart', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Gagny', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Lormont', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rennes', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lille', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Dieppe', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Quimper', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Wuppertal', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Duisburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Amsterdam', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Charleroi', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Pulheim', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Berne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Concarneau', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ajaccio', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Le Petit-Quevilly', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Langenhagen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Siegen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Reutlingen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Schwerin', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Utrecht', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Nieuwegein', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Hamm', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Genk', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Oberhausen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Emmen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('La Roche-sur-Yon', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Graz', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Creil', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Eindhoven', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('La Rochelle', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Haarlem', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bagneux', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dortmund', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Reims', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ingolstadt', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Noisy-le-Grand', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Givors', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Heerlen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('The Hague', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Mulhouse', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Vitrolles', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Clermont-Ferrand', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Lens', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Unna', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Halle', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Istres', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Hanover', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Offenburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Remscheid', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cagnes-sur-Mer', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Vanves', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Leeuwarden', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bremen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Le Pré-Saint-Gervais', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bry-sur-Marne', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bayonne', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Aubervilliers', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Zeist', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Aix-en-Provence', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gonesse', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Gennevilliers', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Guyancourt', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Lippstadt', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bonn', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Oyonnax', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Vlaardingen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Breda', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Poitiers', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Arles', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Toulon', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Purmerend', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Gien', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Digne-les-Bains', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Draguignan', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Weimar', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rouen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bar-le-Duc', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Boulogne-sur-Mer', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Six-Fours-les-Plages', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Burgerbrug', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Innsbruck', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Orsay', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Albi', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Mougins', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Krefeld', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Velbert', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cologne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Lucerne', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Geneva', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Sarreguemines', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Laon', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Clichy', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Cognac', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Pierre-des-Corps', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Fresnes', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Noisy-le-Sec', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bagnolet', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Roissy-en-Brie', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Frankfurt', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Dorsten', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Essen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Erfurt', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Erlangen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Emden', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Viersen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montauban', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Rotterdam', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Mechelen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Leuven', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Tourcoing', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bonneuil-sur-Marne', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bourg-en-Bresse', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rillieux-la-Pape', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Landerneau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Niort', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Wattrelos', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Le Havre', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saumur', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Aalen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Moers', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Euskirchen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Hildesheim', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Tilburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Castrop-Rauxel', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Le Mans', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Hardenberg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Vichy', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Meudon', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Alfortville', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gap', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Paderborn', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Athis-Mons', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Menton', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Le Pontet', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Eragny', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Miramas', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Munster', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Hazebrouck', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Quentin', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gummersbach', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Lausanne', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Villemomble', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Tarbes', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Cournon-d\'Auvergne', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Freiburg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Stains', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Minden', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Slootdorp', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Douai', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Puteaux', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Villejuif', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Castres', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Cottbus', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Moulins', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Marl', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Arnhem', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Heidelberg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Groningen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wels', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Montigny-le-Bretonneux', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montreuil', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Fontenay-le-Comte', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Michel-sur-Orge', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ghent', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Mitry-Mory', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Limay', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Grigny', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Le Blanc-Mesnil', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lagny-sur-Marne', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Witten', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Poissy', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Libourne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Solingen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Kaiserslautern', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Maastricht', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carcassonne', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Lisieux', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Laval', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Martigues', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Carpentras', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Maisons-Laffitte', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Le Chesnay', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Les Clayes-sous-Bois', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Gladbeck', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Troisdorf', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sallanches', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Pontivy', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dinslaken', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Oss', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Les Pennes-Mirabeau', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Roubaix', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Neuilly-sur-Marne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rostock', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Louviers', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Schiedam', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Versailles', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Les Ulis', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Corbeil-Essonnes', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Sindelfingen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Caen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Borken', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Hagen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Chamond', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Fontainebleau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vertou', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Mannheim', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Ennigerloh', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Neunkirchen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Longjumeau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Neuilly-Plaisance', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Tremblay-en-France', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Dormagen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('La Seyne-sur-Mer', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Frontignan', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Salon-de-Provence', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carquefou', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Berck', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Forbach', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Chaumont', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Senlis', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Aix-les-Bains', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Ludwigsburg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Iserlohn', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bottrop', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('St. Gallen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montgeron', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Annecy', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Narbonne', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('La Teste-de-Buch', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Roanne', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bamberg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Basel', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Vesoul', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wasquehal', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Regensburg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Neu-Ulm', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Grevenbroich', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Gelsenkirchen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pamiers', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bremerhaven', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Recklinghausen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Norderstedt', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Willich', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Enschede', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Helmond', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Kortrijk', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Trappes', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Choisy-le-Roi', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bastia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Tournai', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Lorient', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Castelnau-le-Lez', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Hattingen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Flensburg', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Calais', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cachan', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Villenave-d\'Ornon', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Loos', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Verdun', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Montceau-les-Mines', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sceaux', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Vernon', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Hayange', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lohne', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gera', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Stadtlohn', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Wolfsburg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Kerpen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Winterthur', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Olivet', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Maubeuge', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Courbevoie', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Oldenburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Zwolle', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Doetinchem', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Uithoorn', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Dole', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Douarnenez', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Les Pavillons-sous-Bois', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Villiers-sur-Marne', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Chelles', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Blanquefort', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Firminy', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Oullins', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Mantes-la-Ville', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Millau', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Sorgues', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Pierrefitte-sur-Seine', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Montrouge', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Avon', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Montbrison', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('La Celle-Saint-Cloud', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Lattes', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Colombes', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Les Mureaux', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Auch', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Herford', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Dizier', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Biarritz', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Cyr-sur-Loire', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Langenfeld', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Hilversum', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Barneveld', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Roermond', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Rochefort', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Riom', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Thonon-les-Bains', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Villeparisis', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Mont-Saint-Aignan', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Brive-la-Gaillarde', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cavaillon', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Savigny-le-Temple', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Grenoble', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Malakoff', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Suresnes', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Menden', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Worms', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Potsdam', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Erftstadt', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bron', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Lanester', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Vallauris', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Friedberg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Herne', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hamme', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carvin', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Gardanne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Voiron', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('La Chapelle-sur-Erdre', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ludwigshafen am Rhein', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Meaux', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Pontoise', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Clichy-sous-Bois', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Flers', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Wilhelmshaven', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sucy-en-Brie', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Rueil-Malmaison', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Verviers', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Maisons-Alfort', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Rambouillet', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('La Madeleine', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Darmstadt', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Toul', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Villingen-Schwenningen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hautmont', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Deventer', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Laurent-du-Var', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Franconville', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Passau', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Greifswald', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Gradignan', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Goussainville', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Ploemeur', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Mouscron', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Koblenz', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Neuwied', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Herten', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Annonay', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ivry-sur-Seine', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Plaisance-du-Touch', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Melun', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Rosny-sous-Bois', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bressuire', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Villeneuve-d\'Ascq', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Villeneuve-Saint-Georges', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Amersfoort', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Lons-le-Saunier', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Annemasse', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Issoire', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Kalundborg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Dublin', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Middlesbrough', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bruree', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bergen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Coventry', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Whitley', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Guildford', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('York', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Reading', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Blackpool', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Randers', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bournemouth', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Preston', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bognor Regis', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Oxford', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Southport', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Frederiksberg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Garforth', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Eastbourne', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Aylesbury', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Vantaa', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Stockport', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Goring-on-Thames', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Sunderland', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hove', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Trawden Forest', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Oslo', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Stavanger', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Dudley', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Letchworth', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Hartlepool', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Oldham', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Worcester', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wolverhampton', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Brighton', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Basingstoke', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Mickleby', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Derby', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('St. Kew', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Copenhagen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Kingston on Soar', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Stevenage', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Graveney with Goodnestone', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Halmstad', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Horsey', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('St. Michael Penkevil', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Liverpool', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Redditch', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Birkenhead', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Peterborough', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Watford', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Nottingham', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dartford', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Haninge', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('West Leake', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Portsmouth', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bristol', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Chelmsford', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bath', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Helsingborg', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Knotting', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cardiff', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rottingdean', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Hinckley', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hereford', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Norwich', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Solihull', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Weston-super-Mare', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Darlington', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ashford', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Solna', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Exeter', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Alby with Thwaite', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Swansea', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Warrington', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cropton', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Plymouth', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Blackburn', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Crewe', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Shrewsbury', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Wallasey', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Walsall', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Gloucester', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Tamworth', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Chesterfield', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bideford', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Kotka', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Halifax', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wooler', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Chatham', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Lincoln', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Dronfield', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Livingston', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Hamar', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Kilwinning', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Southampton', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cheltenham', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Upplands Väsby', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Barton in Fabis', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Battipaglia', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bologna', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Altamura', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Cartagena', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Tivoli', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Jerez de la Frontera', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Talavera de la Reina', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Potenza', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Turin', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pamplona', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Reggio nell\'Emilia', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Chieti', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Treviso', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Badalona', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bilbao', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vigo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Batalha', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Valladolid', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Elx', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Portici', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Lisbon', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Majadahonda', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Palermo', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Grosseto', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Perugia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('El Ejido', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Fuenlabrada', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Benevento', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Oviedo', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Civitavecchia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Sesto San Giovanni', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rovigo', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Venice', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('La Spezia', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Barakaldo', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Orihuela', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Avellino', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Brescia', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Pontevedra', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Como', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Getafe', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Palencia', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Velletri', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Pescara', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Faenza', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Girona', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Trieste', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Paredes', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Acireale', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ponferrada', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Torre del Greco', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Marsala', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Marbella', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Huelva', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Viterbo', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vigevano', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cremona', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Pomezia', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Brindisi', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Vittoria', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Prato', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Quartu Sant\'Elena', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cinisello Balsamo', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Manresa', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Alcobendas', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Granollers', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Latina', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Falconara Marittima', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Parma', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Pistoia', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Massa', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Casoria', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Capua', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('El Escorial', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Valdemoro', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Coslada', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Melilla', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Segovia', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Ferrara', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Siena', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Modena', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carrara', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Crotone', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Imola', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Busto Arsizio', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Pisa', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Asti', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Manfredonia', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Arganil', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Guidonia Montecelio', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Fuengirola', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Reus', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Mijas', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Boscoreale', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Barletta', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('San Severo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Lucca', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Loures', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Zamora', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Terras de Bouro', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vagos', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Chiclana de la Frontera', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Den Helder', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Ris-Orangis', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Dreux', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Friedrichshafen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Brussels', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Echirolles', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Garbsen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Louis', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Chevilly-Larue', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Massy', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Soissons', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Montmorency', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Villefontaine', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bad Waldsee', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Venlo', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Roosendaal', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Coudekerque-Branche', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Fontenay-sous-Bois', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Herblain', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Ratingen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Almelo', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Aalst', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Roeselare', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Chatou', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bondy', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Allauch', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Rheine', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Bayreuth', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Delmenhorst', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Auxerre', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Les Herbiers', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Thionville', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lannion', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Schweinfurt', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Gronau', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Villeneuve-le-Roi', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Anglet', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Mauguio', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Rosenheim', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Spijkenisse', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Torcy', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Outreau', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Vaulx-en-Velin', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Agen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Evreux', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cluses', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Leverkusen', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Nogent-sur-Oise', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Hengelo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Illkirch-Graffenstaden', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bruges', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Agde', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('La Ciotat', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Mons-en-Baroeul', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Valenciennes', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Marly-le-Roi', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Sannois', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Detmold', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Le Cannet', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Jean-de-la-Ruelle', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Fulda', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Peer', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Dax', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Germain-en-Laye', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Colomiers', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Blois', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Faches-Thumesnil', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ronchin', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Elbeuf', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Veenendaal', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Troyes', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bobigny', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Schiffweiler', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Waiblingen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sartrouville', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Langen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Naumburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lingolsheim', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Terneuzen', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Halluin', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Cambrai', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Garches', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Annecy-le-Vieux', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ipswich', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Doncaster', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Knook', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Landskrona', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Aberdeen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Clontarf', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sonderborg', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Drammen', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Kristiansand', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Halesowen', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Kettering', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Paisley', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Worthing', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Bracknell', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('East Kilbride', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gillingham', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Nuneaton', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Duddington-with-Fineshade', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Dunstable', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Montecatini Terme', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Lora del Río', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Carpi', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Modica', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Arezzo', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Capannori', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Vignola', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Rubí', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Dos Hermanas', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('El Prat de Llobregat', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Andria', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Lugo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Teramo', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Gandia', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Getxo', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Lecce', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Trento', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Piacenza', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Agrigento', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Caserta', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Odivelas', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Pesaro', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Chioggia', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Afragola', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Toledo', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Gela', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cosenza', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Savona', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Lorca', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Fano', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Alessandria', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Ragusa', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Ponteareas', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Acerra', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Santiago de Compostela', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Foligno', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Legnano', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Treviglio', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Anzio', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Varese', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Guadalajara', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Lunel', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Tournefeuille', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Tulle', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Denain', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('La Baule-Escoublac', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Klagenfurt', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Eggenstein-Leopoldshafen', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Montereau-Fault-Yonne', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Stralsund', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Vence', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Bergerac', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sanary-sur-Mer', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Stolberg', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Günzburg', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Saint-Gratien', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cestas', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Villeneuve-la-Garenne', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Sète', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Leiden', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Caluire-et-Cuire', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Le Creusot', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Fleury-les-Aubrais', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bourgoin-Jallieu', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Plaisir', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Wakefield', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Northwich', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Briton Ferry', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bebington', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Widmerpool', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Kidderminster', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Warthill', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cumbernauld', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Morley', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Clydach', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Eskilstuna', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Gallarate', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Cercola', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Bergamo', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Cártama', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Ancona', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cuneo', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Bitonto', 'prasad');
INSERT INTO City_list (City, Manger) VALUES ('Trani', 'raj');
INSERT INTO City_list (City, Manger) VALUES ('Badajoz', 'Kumar');
INSERT INTO City_list (City, Manger) VALUES ('Torremolinos', 'rao');
INSERT INTO City_list (City, Manger) VALUES ('Cuenca', 'Mohan');
INSERT INTO City_list (City, Manger) VALUES ('Sagunto', 'prasad');

DROP TABLE IF EXISTS Country_list;

CREATE TABLE Country_list (
    Country	VARCHAR(512),
    Group_Color	VARCHAR(512),
    CC_rank	VARCHAR(512),
    Zone	VARCHAR(512)
);

INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('United Kingdom', 'Green', 'CC-01', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('France', 'Green', 'CC-02', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Germany', 'Green', 'CC-03', 'East');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Italy', 'Green', 'CC-04', 'North');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('UAE', 'Green', 'CC-05', 'East');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('China', 'red', 'CC-06', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Sweden', 'red', 'CC-07', 'North');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Belgium', 'red', 'CC-08', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Austria', 'Yellow', 'CC-09', 'North');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Ireland', 'Yellow', 'CC-10', 'South');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Portugal', 'Yellow', 'CC-11', 'North');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Bangladesh', 'Yellow', 'CC-12', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Denmark', 'Yellow', 'CC-13', 'East');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Norway', 'Yellow', 'CC-14', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Switzerland', 'Yellow', 'CC-15', 'West');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('India', 'White', 'CC-16', 'East');
INSERT INTO Country_list (Country, Group_Color, CC_rank, Zone) VALUES ('Srilanka', 'White', 'CC-17', 'West');

DROP TABLE IF EXISTS Manager_list;

CREATE TABLE Manager_list (
    Manager	VARCHAR(512),
    Mobile_number	bigint,
    Gender	VARCHAR(512)
);

INSERT INTO Manager_list (Manager, Mobile_number, Gender) VALUES ('raj', '8777522091', 'Male');
INSERT INTO Manager_list (Manager, Mobile_number, Gender) VALUES ('Kumar', '9781422166', 'Male');
INSERT INTO Manager_list (Manager, Mobile_number, Gender) VALUES ('rani', '8957994638', 'Female');
INSERT INTO Manager_list (Manager, Mobile_number, Gender) VALUES ('rajesh', '8978264834', 'Male');
INSERT INTO Manager_list (Manager, Mobile_number, Gender) VALUES ('prasad', '8898191029', 'Male');

DROP TABLE IF EXISTS Emp_Data;

CREATE TABLE Emp_Data (
    Emp_ID	INT,
    Name	VARCHAR(512),
    City	VARCHAR(512),
    Manager_ID	INT
);

INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1001', 'raj', 'Hyd', '1009');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1002', 'kumar', 'Del', '1009');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1003', 'rao', 'Bang', '1009');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1004', 'Mohan', 'Hyd', '1006');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1005', 'Prasad', 'Del', '1006');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1006', 'Varma', 'Bang', '1004');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1007', 'Sharma', 'Hyd', '1004');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1008', 'raju', 'Del', '1004');
INSERT INTO Emp_Data (Emp_ID, Name, City, Manager_ID) VALUES ('1009', 'kumari', 'Bang', '1004');


CREATE TABLE Self (
    Emp_ID	INT,
    Name	VARCHAR(512),
    City	VARCHAR(512),
    Manager_ID	INT
);

INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1001', 'raj', 'Hyd', '1009');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1002', 'kumar', 'Del', '1009');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1003', 'rao', 'Bang', '1009');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1004', 'Mohan', 'Hyd', '1006');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1005', 'Prasad', 'Del', '1006');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1006', 'Varma', 'Bang', '1004');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1007', 'Sharma', 'Hyd', '1004');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1008', 'raju', 'Del', '1004');
INSERT INTO Self (Emp_ID, Name, City, Manager_ID) VALUES ('1009', 'kumari', 'Bang', '1004');
